### ISSUE TITLE
gitignore / npmignore

### ISSUE THREAD

**Issue by mattdesl** [stackgl/stackgl-generator#2]
two small issues:
1. gitignore template does not get added to the module during creation, because it is ignored during `npm install stackgl-generator`
2. the npmignore file gets published to NPM; this can be avoided by including `.npmignore` in itself 

To avoid all the annoyances with npm / git ignores I've just done a stupid simple fix in my fork:
https://github.com/mattdesl/module-generator/blob/master/index.js#L56

**Comment by hughsk** [comment]
Fixed by #3 :)
